version: '3.9'
services:
  jammy-aio:
    image: devcontainer/aio:latest
    build:
      dockerfile: dev.dockerfile
      target: java-dev-alt
      platforms:
        - "linux/amd64"
      args:
        - OS_DIST=jammy
  jammy-node14:
    image: devcontainer/node:jammy-fe
    build:
      dockerfile: dev.dockerfile
      target: frontend-dev
      platforms:
        - "linux/amd64"
      args:
        - OS_DIST=jammy
  jammy-jdk17:
    image: devcontainer/java:jammy-17
    build:
      dockerfile: dev.dockerfile
      target: java-dev
      platforms:
        - "linux/amd64"
      args:
        - OS_DIST=jammy
        - JDK_VERSION=17
        - INSTALL_JDK_SRC=1
  jammy-jdk15:
    image: devcontainer/java:jammy-15
    build:
      dockerfile: dev.dockerfile
      target: java-dev
      platforms:
        - "linux/amd64"
      args:
        - OS_DIST=jammy
        - JDK_VERSION=15
        - INSTALL_JDK_SRC=1
  jammy-jdk8:
    image: devcontainer/java:jammy-8
    build:
      dockerfile: dev.dockerfile
      target: java-dev
      platforms:
        - "linux/amd64"
      args:
        - OS_DIST=jammy
        - JDK_VERSION=8
        - INSTALL_JDK_SRC=1
