version: "3.9"

name: dev_infra

networks:
  default:
    name: dev-infra
    # docker network create dev-infra
    external: true

volumes:
  sonar-data:
  sonar-logs:
  sonar-exts:
  sonar-db:
  openldap_data:

services:

  # Zookeeper standalone
  zookeeper:
    platform: linux/amd64
    image: wurstmeister/zookeeper:latest
    networks:
      default:
        aliases:
          - zookeeper.local
    ports:
      - 2181:2181
    restart: unless-stopped

  # Kafka standalone
  kafka:
    platform: linux/amd64
    image: wurstmeister/kafka:latest
    environment:
      - KAFKA_ZOOKEEPER_CONNECT
      - KAFKA_ADVERTISED_HOST_NAME
    networks:
      default:
        aliases:
          - kafka.local
    ports:
      - 9092:9092
    restart: unless-stopped
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    profiles:
      - debug
    depends_on:
      - kafka
    ports:
      - 9103:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
      - KAFKA_CLUSTERS_1_NAME
      - KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS
      - DYNAMIC_CONFIG_ENABLED
    # volumes:
    #   - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml

  # Redis standalone
  redis:
    platform: linux/amd64
    image: redis:alpine
    networks:
      default:
        aliases:
          - redis.local
    ports:
      - 6379:6379
    restart: unless-stopped

  plantuml:
    image: plantuml/plantuml-server:jetty
    ports:
      - 9999:8080
    restart: unless-stopped
    environment:
      - BASE_URL
      - PLANTUML_LIMIT_SIZE
      - PLANTUML_STATS
      - HTTP_AUTHORIZATION
      - ALLOW_PLANTUML_INCLUDE

  sonar:
    # image: sonarqube:lts-community
    image: sonarqube:lts-developer
    profiles:
      - extend
    depends_on:
      - sonardb
    ports:
      - 9000:9000
    restart: unless-stopped
    stop_grace_period: 1m30s
    # sysctl: see .wslconfig
    ulimits:
      nproc: 8192
      nofile: 131072
    environment:
      - SONAR_JDBC_URL
      - SONAR_JDBC_USERNAME
      - SONAR_JDBC_PASSWORD
      - SONAR_SECURITY_REALM
      - SONAR_AUTHENTICATOR_DOWNCASE
      - LDAP_URL
      - LDAP_USER_BASEDN
      - LDAP_USER_REQUEST
      - LDAP_USER_REALNAMEATTRIBUTE
      - LDAP_USER_EMAILATTRIBUTE
      - LDAP_BINDDN
      - LDAP_BINDPASSWORD
    volumes:
      - sonar-data:/opt/sonarqube/data
      - sonar-logs:/opt/sonarqube/logs
      - sonar-exts:/opt/sonarqube/extensions
  sonardb:
    image: postgres:15-alpine
    profiles:
      - extend
    networks:
      default:
        aliases:
          - sonarqube.local
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - sonar-db:/var/lib/postgresql/data
  openldap:
    image: bitnami/openldap:2.6
    profiles:
      - extend
    ports:
      - 1389:1389
      # - 1636:1636 # LDAPS
    restart: unless-stopped
    environment:
      - LDAP_ROOT
      - LDAP_ADMIN_USERNAME
      - LDAP_ADMIN_PASSWORD
      - LDAP_USERS
      - LDAP_PASSWORDS
      - LDAP_PASSWORD_HASH
    volumes:
      - openldap_data:/bitnami/openldap
