version: '3.9'
networks:
  default:
    name: dev-infra
    external: true
services:
  www:
    image: nginx:stable-alpine
    environment:
      TZ: "Europe/Moscow"
    ports:
      - 80:80
      - 8088:80
    restart: unless-stopped
    volumes:
      - ./${BRAND:?}-client-portal/dist:/usr/share/nginx/html/cp:ro
      - ./${BRAND:?}-ib-portal/dist:/usr/share/nginx/html/ib:ro
      - ./www.conf:/etc/nginx/conf.d/default.conf:ro
