version: '3.9'
networks:
  default:
    name: dev-infra
    external: true
services:
  www:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 8088:80
    restart: unless-stopped
    volumes:
      - ./www:/usr/share/nginx/html:ro
      - ./www.conf:/etc/nginx/conf.d/default.conf:ro
